### ISSUE TITLE
Add rest endpoint to run program one-shot

### ISSUE THREAD

**Issue by mstemm** [juttle/outrigger#120]
Add a rest endpoint to outrigger to run a program from a path and receive that program's output as the http response. This endpoint would provide an alternative to opening a websocket to receive the stream of jsdp messages.

**Comment by jadbox** [comment]
Does the scope of this task include updating the juttle client/viz to work with a Rest response, or is that a separate ticket for those repos?

**Comment by jadbox** [comment]
Alternatively, our web server controller could stream from Outrigger and convert that entire stream as an object to send to the Juttle client via Rest request... although the Juttle client would still need to support receiving data by Rest interface.

**Comment by demmer** [comment]
@jadbox This task just covers the server-side portion. The idea is to add an API endpoint to run a juttle and get the outputs in a single request.

Then the client side application would hit an endpoint on your web server controller which would perform any necessary authentication and transformation on the API request, and then in turn make the HTTP request to outrigger to run the juttle program, consume and possibly transform the response, then return the data points back to the client, which would instantiate the charts and render them. It seems to me that your web controller could just use a standard http client library since there wouldn't be too much coordination needed.

I'm going to put together a simple gist showing this all working as an example for you guys to follow.

**Comment by jadbox** [comment]
Great. Is there a task for juttle-client to accept a Restful payload? Or is it possible to side-step juttle-client and just make the call directly and feed that into juttle-viz?

**Comment by jadbox** [comment]
@demmer @mstemm When possible, can you provide a "no-op" / empty example Restful response from outrigger? I want to stub out our server to return that response to the view so that I'm not stuck on this.

**Comment by mstemm** [comment]
The proposed format is in PR #125. Take a look at the additions to docs/jsdp.md. This format might change as I get a review but it's a good starting point.
