### ISSUE TITLE
Example stock_prices.juttle doesn't work with non-default input

### ISSUE THREAD

**Issue by dmehra** [juttle/outrigger#83]
Noticed yesterday that `examples/core-juttle/stock_prices.juttle` only works if run with the default input "IBM". For any other input, it doesn't even seem to execute. It was working correctly at some point within last week, not sure when the regression occurred.

**Comment by demmer** [comment]
The issue isn't actually that it can't run with other symbols, since you can change the symbol before running the first time.

The problem is that for some reason when re-running the program with a new input value, something triggers an options validation error coming from the timechart.

This is related to the `-display.dataDensity 0` option. If I remove that, then things seem to work properly.

**Comment by demmer** [comment]
@go-oleg Can you take a look at this?

**Comment by go-oleg** [comment]
Did some looking into this, and there are at least two problems working in tandem against us here.

It appears the `view.js` component gets mounted after the second play click _before_ a new set of view options is received from the server. This is most likely because the job_id has been updated in the store, but the new view options haven't come across the wire yet and are not in the store. This coupled with the fact that the views sometimes mutate the options passed in (filed https://github.com/juttle/juttle-viz/issues/24 for this) means the options being passed in are not equal from a value-perspective to the options passed in originally (because they were mutated by the view) and thus fail some of the parameter validation. @mnibecker, can you look into reinstantiating the views once the new options have been received as opposed to when the job_id changes? I believe this is a bug on juttle-client-library as opposed to outrigger.
